/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CheckboxInput: typeof import('./composables/useFormBuilder/_inputs/CheckboxInput')['CheckboxInput']
  const ComboBoxInput: typeof import('./composables/useFormBuilder/_inputs/ComboBoxInput')['ComboBoxInput']
  const CustomInput: typeof import('./composables/useFormBuilder/_inputs/CustomInput')['CustomInput']
  const DateInput: typeof import('./composables/useFormBuilder/_inputs/DateInput')['DateInput']
  const EffectScope: typeof import('vue')['EffectScope']
  const NumberInput: typeof import('./composables/useFormBuilder/_inputs/NumberInput')['NumberInput']
  const RadioGroupInput: typeof import('./composables/useFormBuilder/_inputs/RadioGroupInput')['RadioGroupInput']
  const SelectInput: typeof import('./composables/useFormBuilder/_inputs/SelectInput')['SelectInput']
  const TextInput: typeof import('./composables/useFormBuilder/_inputs/TextInput')['TextInput']
  const TextareaInput: typeof import('./composables/useFormBuilder/_inputs/TextareaInput')['TextareaInput']
  const cn: typeof import('./lib/utils')['cn']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defaultToast: typeof import('./lib/toast/defaultToast')['defaultToast']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const errorToast: typeof import('./lib/toast/errorToast')['errorToast']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const httpClient: typeof import('./lib/httpClient/index')['httpClient']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const successToast: typeof import('./lib/toast/successToast')['successToast']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useFormBuilder: typeof import('./composables/useFormBuilder/index')['useFormBuilder']
  const useId: typeof import('vue')['useId']
  const useLink: typeof import('vue-router')['useLink']
  const useLocalStorageItem: typeof import('./composables/useLocalStorageItem')['useLocalStorageItem']
  const useModel: typeof import('vue')['useModel']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouteParams: typeof import('./composables/useRouteParams')['useRouteParams']
  const useRouteQuery: typeof import('./composables/useRouteQuery')['useRouteQuery']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useToken: typeof import('./composables/useToken')['useToken']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const zod: typeof import('./lib/zod/index')['zod']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { HttpClientRoute } from './lib/httpClient/index'
  import('./lib/httpClient/index')
  // @ts-ignore
  export type { CodegenRoutes } from './lib/httpClient/outputType.d'
  import('./lib/httpClient/outputType.d')
  // @ts-ignore
  export type { CheckboxInputProps, CheckboxInputDef } from './composables/useFormBuilder/_inputs/CheckboxInput'
  import('./composables/useFormBuilder/_inputs/CheckboxInput')
  // @ts-ignore
  export type { ItemComboBox, ComboBoxInputProps, ComboBoxInputDef } from './composables/useFormBuilder/_inputs/ComboBoxInput'
  import('./composables/useFormBuilder/_inputs/ComboBoxInput')
  // @ts-ignore
  export type { CutsomInputProps, CustomInputDef } from './composables/useFormBuilder/_inputs/CustomInput'
  import('./composables/useFormBuilder/_inputs/CustomInput')
  // @ts-ignore
  export type { DateInputProps, DateInputDef } from './composables/useFormBuilder/_inputs/DateInput'
  import('./composables/useFormBuilder/_inputs/DateInput')
  // @ts-ignore
  export type { NumberInputProps, NumberInputDef } from './composables/useFormBuilder/_inputs/NumberInput'
  import('./composables/useFormBuilder/_inputs/NumberInput')
  // @ts-ignore
  export type { ItemRadioGroup, RadioGroupProps, RadioGroupDef } from './composables/useFormBuilder/_inputs/RadioGroupInput'
  import('./composables/useFormBuilder/_inputs/RadioGroupInput')
  // @ts-ignore
  export type { ItemSelect, SelectInputProps, SelectInputDef } from './composables/useFormBuilder/_inputs/SelectInput'
  import('./composables/useFormBuilder/_inputs/SelectInput')
  // @ts-ignore
  export type { TextInputProps, TextInputDef } from './composables/useFormBuilder/_inputs/TextInput'
  import('./composables/useFormBuilder/_inputs/TextInput')
  // @ts-ignore
  export type { TextareaInputProps, TextareaInputDef } from './composables/useFormBuilder/_inputs/TextareaInput'
  import('./composables/useFormBuilder/_inputs/TextareaInput')
  // @ts-ignore
  export type { BaseInputDef, InputProps, FormInputDef, GetSlots, SlotObject, FormInputToRecordRef, ResultCheckForm } from './composables/useFormBuilder/types.d'
  import('./composables/useFormBuilder/types.d')
}
