/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormControl: typeof import('./components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./components/ui/form/FormMessage.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
