// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/login";
    body: {
        email: string;
        password: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "user.logged";
        body: {
            token: string;
        };
    };
}) | ({
    method: "GET";
    path: "/bikes";
    query: {
        page: number;
    };
    headers?: {
        token?: string | undefined;
    } | undefined;
    response: {
        code: 403;
        information: "token.invalid";
        body?: undefined;
    } | {
        code: 404;
        information: "manager.notfoud";
        body?: undefined;
    } | {
        code: 200;
        information: "bikes.get";
        body: {
            vin: string;
            modelName: string;
            registration: string;
            factoryYear: number;
            mileage: number;
            purchaseDate: Date;
            stillInCirculation: boolean;
            lastInterviewDate: Date;
        }[];
    };
}) | ({
    method: "GET";
    path: "/bike-models";
    query: {
        page: number;
    };
    headers?: {
        token?: string | undefined;
    } | undefined;
    response: {
        code: 403;
        information: "token.invalid";
        body?: undefined;
    } | {
        code: 404;
        information: "manager.notfoud";
        body?: undefined;
    } | {
        code: 200;
        information: "bikeModels.get";
        body: {
            name: string;
            type: "roadster" | "trail" | "sport" | "touring";
            interviewIntervalByKillometers: number;
            interviewIntervalByDay: number;
        }[];
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
